Repository logstash-plugins/logstash-input-http, pull requests merged in 2022-04, with the labels that each got.

#153 Codec pipeline context
  spec/inputs/http_spec.rb
Labels: status:approved

#151 Feat: review and deprecate ssl protocol/cipher settings
  CHANGELOG.md
  VERSION
  docs/index.asciidoc
  lib/logstash/inputs/http.rb
  spec/inputs/http_spec.rb
  src/main/java/org/logstash/plugins/inputs/http/util/SslSimpleBuilder.java
Labels: status:changes-requested

#154 Doc: Update deprecation notices to standard
  docs/index.asciidoc
Labels: docs, status:approved
